env: "local"

http_server:
  address: "localhost"
  port: 8080
  timeout: 4s
  idle_timeout: 60s

database:
  host: localhost
  port: 5432
  user: postgres
  password: 14078068
  dbname: postgres
  max_conns: 20